#!/usr/bin/env python3
"""
Palaeo-rotate candidate MEIH glacial deposits to 600 Ma
T. Wong Hearing
19 June 2026

This rotation script should be run first before any additional analyses or figure generation. 
Figures (e.g. 2, 3) are generated by separate scripts. 
 
This script creates and then uses locally hosted GPlates rotation files. 
The first run through will download and cache the necessary GPlates files so that future 
use doesn't require a callout to the GPlates server. 

Script logic: 
    - load deposits from the Data_S1...xlsx file sheet csl_deposits 
    - treat deposits with average_longitude == average_latitude == 0 as having no coordinates (NaN) 
        and drop them from the rotation
    - palaeo-rotate average coordinates for every deposit with a likely interval of MEIH or Ediacaran 
        to 600 Ma on the PALEOMAP and MERDITH2021 rotation models
    - summarise rotated deposits by score (all | 4 | 3 | 2 | 1)
"""

# --- load libraries -----------------------------------------------------------------------------
from pathlib import Path
import numpy as np
import pandas as pd
from gplately import PlateModelManager, PlateReconstruction, Points

# --- paths --------------------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[2]          
DATA_DIR = ROOT / "data"
DEPOSITS_XLSX = DATA_DIR / "Data_S1_MEIH_deposits_raw.xlsx"
MODELS_DIR = DATA_DIR / "plate_models"              # gplately cache (git-ignored)
PROCESSED_DIR = DATA_DIR / "processed"              # outputs (git-ignored)
OUTPUT_CSV = PROCESSED_DIR / "meih_deposits_rotated.csv"
SUMMARY_CSV = PROCESSED_DIR / "table_3_meih_deposit_summary_by_score.csv"

# --- parameters ---------------------------------------------------------------------------------
ROTATION_AGE = 600    # Ma
# column suffix -> gplately model name
ROT_MODELS = {
    "PAL": "paleomap",       # Scotese & Wright (2018) PALEOMAP
    "M21": "merdith2021",    # Merdith et al (2021)
}
# rotate deposits with the following likely interval assignments
ROTATE_INTERVALS = ("MEIH", "Ediacaran")
# deposits to exclude 
# these deposits are not relevant for determining proximal glacial conditions
DROP_DEPOSITS = ("Doushantuo glendonites", "Doushantuo Formation")
# score groups for the summary table: will summarise by "all" and each score
SUMMARY_SCORES = (4, 3, 2, 1)

# --- functions ----------------------------------------------------------------------------------
## --- load and filter deposits ------------------------------------------------------------------
def load_deposits(path: Path, intervals=ROTATE_INTERVALS) -> pd.DataFrame:
    """
    Return deposits of given intervals with valid (not [0,0]/[NaN/NaN]) average coordinates.
    """
    cols = [
        "deposit_name",
        "likely_interval",
        "deposit_score_WH02",
        "average_longitude",
        "average_latitude",
    ]
    df = pd.read_excel(path, sheet_name="csl_deposits")[cols]

    # (0, 0) is a placeholder for "no coordinates" -> NaN
    zero = (df["average_longitude"] == 0) & (df["average_latitude"] == 0)
    df.loc[zero, ["average_longitude", "average_latitude"]] = np.nan

    keep = df[
        df["likely_interval"].isin(intervals)
        & ~df["deposit_name"].isin(DROP_DEPOSITS)
        & df["average_longitude"].notna()
        & df["average_latitude"].notna()
    ].copy()
    return keep.reset_index(drop=True)

## --- get rotation models -----------------------------------------------------------------------
def build_reconstruction(model_name: str, data_dir: Path) -> PlateReconstruction:
    """
    Download (first time round) or load from cache (subsequent times) a plate model and build a reconstruction.
    """
    model = PlateModelManager().get_model(model_name, data_dir=str(data_dir))
    try:
        topologies = model.get_topology_features()
    except Exception:
        topologies = None    # e.g. PALEOMAP has no topological features
    return PlateReconstruction(
        model.get_rotation_model(),
        topology_features=topologies,
        static_polygons=model.get_static_polygons(),
    )

## --- rotate coordinates ------------------------------------------------------------------------
def rotate(recon: PlateReconstruction, lons, lats, age: float):
    """
    Reconstruct coordinates back to ``age`` Ma; return (plon, plat).
    """
    gpts = Points(recon, np.asarray(lons), np.asarray(lats))
    rlons, rlats = gpts.reconstruct(age, return_array=True)
    return rlons, rlats

## --- summarise deposits by score ---------------------------------------------------------------
def summarise_by_score(deposits: pd.DataFrame) -> pd.DataFrame:
    """
    Summarise deposits by score: counts and absolute palaeolatitude summary statistics.

    For all deposits and then for each score value in ``SUMMARY_SCORES``: 
        - report the number of deposits in total (``n_all``) and by likely interval 
          (one ``n_<interval>`` column per ``ROTATE_INTERVALS``), and
        - min / median / mean / sd of ``|palaeolatitude|`` on each rotation model.
    
    Standard deviation is the sample sd and is NaN for groups with fewer than two deposits.
    """    
    df = deposits.copy()
    df["deposit_score_WH02"] = pd.to_numeric(df["deposit_score_WH02"],
                                             errors="coerce")
    df = df[df["deposit_score_WH02"].notna()]
    for suffix in ROT_MODELS:
        df[f"abs_plat_{suffix}"] = df[f"plat_{suffix}"].abs()

    rows = []
    for group in ("all", *SUMMARY_SCORES):
        sub = df if group == "all" else df[df["deposit_score_WH02"] == group]
        row = {"score_group": group, "n_all": len(sub)}
        for interval in ROTATE_INTERVALS:
            row[f"n_{interval}"] = int((sub["likely_interval"] == interval).sum())
        for suffix in ROT_MODELS:
            a = sub[f"abs_plat_{suffix}"]
            row[f"abs_lat_{suffix}_min"] = round(a.min(), 1) if len(a) else np.nan
            row[f"abs_lat_{suffix}_median"] = round(a.median(), 1) if len(a) else np.nan
            row[f"abs_lat_{suffix}_mean"] = round(a.mean(), 1) if len(a) else np.nan
            row[f"abs_lat_{suffix}_sd"] = round(a.std(), 1) if len(a) > 1 else np.nan
        rows.append(row)
    return pd.DataFrame(rows)

## --- main --------------------------------------------------------------------------------------
def main() -> pd.DataFrame:
    deposits = load_deposits(DEPOSITS_XLSX)
    counts = deposits["likely_interval"].value_counts().to_dict()
    print(f"{len(deposits)} deposits with coordinates -> rotating to "
          f"{ROTATION_AGE} Ma  ({counts})")

    for suffix, model_name in ROT_MODELS.items():
        print(f"  [{model_name}] loading model and rotating ...")
        recon = build_reconstruction(model_name, MODELS_DIR)
        plon, plat = rotate(
            recon,
            deposits["average_longitude"].to_numpy(),
            deposits["average_latitude"].to_numpy(),
            ROTATION_AGE,
        )
        deposits[f"plon_{suffix}"] = plon
        deposits[f"plat_{suffix}"] = plat

    PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    deposits.to_csv(OUTPUT_CSV, index=False)
    print(f"wrote {len(deposits)} rotated deposits -> {OUTPUT_CSV}")

    summary = summarise_by_score(deposits)
    summary.to_csv(SUMMARY_CSV, index=False)
    print(f"wrote score summary ({len(summary)} groups) -> {SUMMARY_CSV}")

    return deposits, summary

# --- run ----------------------------------------------------------------------------------------
if __name__ == "__main__":
    deposits, summary = main()
    pd.set_option("display.max_rows", None, "display.width", 200)
    print("\nrotated deposits:")
    print(deposits.to_string(index=False))
    print("\ndeposit summary by score (counts + |palaeolat| stats):")
    print(summary.to_string(index=False))
